name: HotBlock
main: surva\hotblock\HotBlock
version: 1.2.4
api: 5.0.0

softdepend: ["EconomyAPI", "BedrockEconomy", "Capital", "InfoAPI"]

author: survanetwork
description: A funny PvP minigame
website: https://plugins.surva.net/#hotblock
